config/routes.rb
Rails.application.routes.draw do
 
    get "profiles/show"
    
    devise_scope :user do
      get "/register", :to => "devise/registrations#new", :as => :register
      get "/login", :to => "devise/sessions#new", :as => :login
      get "/logout", :to => "devise/sessions#destroy", :as => :logout
      
    end
      
  
    resources :statuses
    get "feed", :to => "statuses#index", :as => :feed
    root to: 'statuses#index'

   

    devise_for :users, skip: [:sessions]

    as :user do
      get "/login" => 'devise/sessions#new', as: :new_user_session
      post "/login" => 'devise/sessions#create', as: :user_session
      delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
    end

    get '/:id', to: "profiles#show", as: 'profile'

    resources :user_friendships

end

app/models/status.rb
class Status < ActiveRecord::Base
	belongs_to :user

	validates :content, { presence: :true, length: { minimum: 2 }}
	validates :user, { presence: true }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  has_many :statuses
  has_many :user_friendships
  has_many :friends, through: :user_friendships

  validates :first_name, presence: true
 
  validates :last_name, presence: true
 
  validates :profile_name, presence: true, 
                           uniqueness: true,
                           format: {
                             with: /\A[a-zA-Z\-\_]+\Z/,
                             message: "Shame on you,format correctly!"
                           }
                           
  has_many :statuses
  has_many :user_friendships
  has_many :friends, through: :user_friendships
                           

  def full_name
  	first_name + ' ' + last_name
  end

  def gravatar_url
    gravatar_email = email.strip
    downcased_email = gravatar_email.downcase
    hash = Digest::MD5.hexdigest(downcased_email)
    "http://www.gravatar.com/avatar/#{hash}"
  end

  def to_param
    profile_name
  end
end

app/models/user_friendship.rb
class UserFriendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'
  
  attr_accessible :user, :friend
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected 

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :first_name << :last_name << :profile_name
  	devise_parameter_sanitizer.for(:account_update) << :first_name << :last_name << :profile_name
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	def show
		@user = User.find_by_profile_name(params[:id])
		if (@user)
      @statuses = @user.statuses.all
			render action: :show
    else
      render file: 'public/404', status: 404, formats: [:html]
    end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_filter :authenticate_user!, only: [ :new, :create, :edit, :update, :destroy ]
  
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    set_status
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
    set_status
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @status }
      else
        format.html { render action: 'new' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    @status = current_user.statuses.find(params[:id])
    if params[:status] && params[:status].has_key?(:user_id)
      params[:status].delete(:user_id)
    end

    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    set_status
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      if (params[:status])
        params.require(:status).permit(:name, :content, :user_id)
      end
    end
  end

app/controllers/user_friendships_controller.rb
class UserFriendshipsController < ApplicationController
  before_filter :authenticate_user!, only: [:new]
  
  def new
    if params[:friend_id]
      @friend = User.where(profile_name: params[:friend_id]).first
      raise ActiveRecord::RecordNotFound if @friend.nil?
      @user_friendship = current_user.user_friendships.new friend: @friend
    else
      flash[:error] = "Friend Required"
    end
  rescue ActiveRecord::RecordNotFound
    render file: 'public/404', status: :not_found
  end

  def create
    if params[:user_friendship] && params[:user_friendship].has_key?(:friend_id)
      @friend = User.where(profile_name: params[:user_friendship][:friend_id]).first
      @user_friendship = current_user.user_friendships.new friend: @friend
      @user_friendship.save
      flash[:notice] = "New friend, #{@friend.full_name}, added!"
      redirect_to profile_path(@friend)
    else
      flash[:error] = "Friend Required"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def flash_class(type)
    case type
    when :alert
      "alert-danger"
    when :notice
      "alert-success"
    else
      ""
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/user_friendships_helper.rb
module UserFriendshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>My Friends</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand" href="#">My Friends</a>
			</div>
			<ul class="nav navbar-nav">
				<li class="active"><%= link_to "All Statuses", feed_path %></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
				<li><%= link_to current_user.full_name, edit_user_registration_path %></li>
				<li><%= link_to "Log Out", logout_path %></li>
				  <% else %>
				<li><%= link_to "Login", login_path %></li>
				<li><%= link_to "Register", register_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
<div class="container">
		<% flash.each do |type, message| %>
		<div class="alert <%= flash_class type %> alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<p><%= message %></p>
		</div>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/profiles/show.html.erb
<div class="page-header">
	<h1><%= @user.full_name %></h1>
  <%= link_to "Add Friend", new_user_friendship_path(friend_id: @user), class: 'btn btn-success' %>
</div>

<% if @statuses %>
<% @statuses.each do |status| %>
<div class="well">
	<%= status.content %>
	  <hr />
	  <%= link_to(time_ago_in_words(status.created_at), status_path(status)) %> ago
  </div>
  <% end %>
<% end %>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class:"form-horizontal"}) do |f| %>
<% if @status.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

  <ul>
    <% @status.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<!-- thank you, internet tutorials for this...! -->
<%= f.input :content %>
<div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Go Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="page-header">
  <h1>All Statuses</h1>
</div>

<%= link_to "Post a New Status", new_status_path, class: "btn btn-success" %>

<% @statuses.each do |status| %>
<div class="status">
  <div class="row">
    <div class="col-md-1 col-xs-1 gravatar">
      <%= link_to image_tag(status.user.gravatar_url), profile_path(status.user) %>
    </div>
    <div class="col-md-7 col-xs-7 content">
      <strong><%= status.user.full_name %></strong>
      <p><%= status.content %></p>
      <div class="meta">
        <%= link_to time_ago_in_words(status.created_at) + " ago", status %>
        <span class="admin">
          | <%= link_to "Edit", edit_status_path(status) %> | 
          <%= link_to "Delete", status, method: :delete, data: { confirm: "Are you sure you want to delete this status?"} %>
        </span>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name: </strong>
  <%= @status.user.full_name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>

app/views/user_friendships/new.html.erb
<p id="notice"><%= notice %></p>
<% if @friend %>
<h1><%= @friend.full_name %></h1>
<p>Do you really want to friend <%= @friend.full_name %>?</p>
<%= form_for @user_friendship, method: :post do |form| %>
<div class="form form-actions">
  <%= form.hidden_field :friend_id, value: @friend.profile_name %>
  <%= submit_tag "Yes, Add Friend", class: 'btn btn-success' %>
  <%= link_to "Cancel", profile_path(@friend), class: 'btn btn-default' %>
</div>
<% end %>
<% end %>